name: demo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^0.1.3
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  progress_dialog:
  image_picker: ^0.8.4+2
  favorite_button: ^0.0.4

  #image_picker: ^0.7.5+2
  flutter_rating_bar: ^4.0.0

  provider: ^5.0.0
  dio: ^4.0.0
  firebase_messaging: ^10.0.4
  firebase_core: ^1.4.0
  flutter_local_notifications: ^6.0.0
  http_parser: ^4.0.0
  collection: ^1.15.0
  zoom_pinch_overlay: ^1.1.2
  like_button: ^2.0.3
  animated_bottom_navigation_bar: ^0.3.2

  cached_network_image: ^3.0.0
  country_pickers: ^2.0.0
  media_picker_widget: ^0.0.4
  carousel_indicator: ^1.0.5
  carousel_slider: ^4.0.0
  share: ^2.0.4
  path_provider: ^2.0.2
  image_cropper: ^1.4.1
  velocity_x: ^3.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
flutter:
  uses-material-design: true

  fonts:

    - family: "Helveticalight"
      fonts:
        - asset: lib/assets/fonts/helvetica-light.ttf
          weight: 400

    - family: "Helvetica"
      fonts:
        - asset: lib/assets/fonts/Helvetica.ttf
          weight: 400

  assets:

    - lib/assets/i18n/en.json
    - lib/assets/logo.png
    - assets/
